### ISSUE TITLE
Can't build on OSX 10.11.2

### ISSUE THREAD

**Issue by awhitex** [Tox/homebrew-tox#30]
$ brew install --HEAD toxic
==> Installing toxic from tox/tox
==> Cloning git://github.com/Tox/toxic
Updating /Library/Caches/Homebrew/toxic--git
==> Checking out branch master
==> make PREFIX='/usr/local/Cellar/toxic/HEAD' DISABLE_DESKTOP_NOTIFY=YES DISABLE_X11=YES
Last 15 lines from /Users/orange/Library/Logs/Homebrew/toxic/01.make:
    ToxAv
/usr/local/Cellar/libtoxcore/HEAD/include/tox/toxav.h:31:23: note: 'ToxAv' declared here
typedef struct _ToxAv ToxAv;
                      ^
In file included from /private/tmp/toxic20160110-8595-11ehnoy/src/chat_commands.c:32:
In file included from /private/tmp/toxic20160110-8595-11ehnoy/src/groupchat.h:30:
/private/tmp/toxic20160110-8595-11ehnoy/src/audio_call.h:87:1: error: unknown type name 'ToxAV'; did you mean 'ToxAv'?
ToxAV *init_audio(ToxWindow *self, Tox *tox);
^~~~~
ToxAv
/usr/local/Cellar/libtoxcore/HEAD/include/tox/toxav.h:31:23: note: 'ToxAv' declared here
typedef struct _ToxAv ToxAv;
                      ^
12 errors generated.
make: *** [/private/tmp/toxic20160110-8595-11ehnoy/build/chat_commands.o] Error 1

**Comment by stal888** [comment]
You need to reinstall toxcore periodically because our formulas don't have versions.

    brew reinstall --HEAD toxcore

It should work after that.
